spring.application.name=payment-service
server.port=8081

management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId}] %logger{36} - %msg%n